upstream fastapi {
    server backend:8080;  # Должно совпадать с именем сервиса в docker-compose
}

server {
    listen 80;
    server_name _;  # Принимать все хосты

    location / {
        proxy_pass http://fastapi;
        include /etc/nginx/servers/proxy_params;
        proxy_set_header Host $http_host;
    }

    location /static/ {
        alias /app/static/;
        expires 30d;
    }

    location /media/ {
        alias /app/media/;
        expires 30d;
    }
}